theme = "hugo-geo-master"
 
[params]

  categories = ["Blog Post","About"] 
  baseURL = "http://casualinferences.com/"
  languageCode = "en-us"
  title = "Casual Inferences"
  subtitle = "A work in progress blog by Michael Elten"
  ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

#Social media buttons!

[[params.socialbuttons]]
	faicon = "twitter"
	url = "https://twitter.com/MichaelElten"

[[params.socialbuttons]]
	faicon = "linkedin"
	url = "https://linkedin.com"

[[params.socialbuttons]]
	faicon = "github"
	url = "https://github.com/MichaelElten"

# Navigation links!
    
[[params.navlinks]]
name= "About me"
url = "about/"  

[[params.navlinks]]
name= "Blog"
url = "post/" 