baseurl = "http://casualinferences.com/"
relativeURLs = false
languageCode = "en-us"
title = "Casual Inferences"
subtitle = "A WIP blog by Michael Elten"
disqusShortname = "shortcode-here"
paginate = 5

[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
	showglobe = true

	favicon = "favicon.ico"

	analytics = "code-here"

	github = "https://github.com/MichaelElten"
	twitter = "https://twitter.com/MichaelElten"
	linkedin = "https://www.linkedin.com/in/michael-elten-496115118/"
	email = "elten.michael@gmail.com"
	
	profilepic = "profile.png"
	
	title = "Casual Inferences"
	subtitle = "A WIP blog by Michael Elten"
	
	[[params.navlinks]]
	name = "About"
	url = "about"
	
	[[params.navlinks]]
	name = "Blog"
	url = ""
	
	[[params.navlinks]]
	name = "Tutorials"
	url = "tutorial/"