theme = "hyde"
[params]
  themeColor = "theme-base-0c"
  description = "My New Blog"
  categories = ["Blog Post","About"]
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Michael's New Hugo Site"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]