---
title: "Presentations"
author: "Michael Elten"
date: '2019-05-20'
Tags: 
- Tutorial
slug: presentations
---

#### This is a list of my previous presentations:
 
*Note: links to presentation materials are provided for illustration purposes only and may only represent preliminary findings that have since changed. Please refer to the publications for final results.*

1. Air pollution and greenness, and the risk of paediatric-onset inflammatory bowel disease. August 2019. International Society of Environmental Epidemiology (ISEE) 2019 Conference. Utrecht, the Netherlands. [Poster](ISEE2019.pdf)

2. Greenness as a protective factor for childhood-onset inflammatory bowel disease? March 2019. University of Ottawa School of Epidemiology and Public Health Research day 2019. Ottawa Canada. [Oral](SEPH2019.pdf)

3. Guidelines for creating effective slideshow presentations. March 2019. Knowledge Translation Event - Canadian Society for Epidemiology and Biostatistics – uOttawa chapter. Ottawa Canada. [Oral](KTEvent.pdf)

4. Ambient air pollution and the risk of childhood-onset inflammatory bowel disease. Feb 2019. CANUE Expert Webinar Series. Online. [Oral](CANUE.pdf)

5.	Evaluating the exposure to ambient air pollution and the risk of pediatric inflammatory bowel disease. Jan 2019. Health Canada Science Forum 2019. Ottawa Canada. [Oral](HCSF2019O.pdf) and [Poster](HCSF2019P.pdf)

6.	Perinatal exposure to ambient air pollution and greenness, and the incidence of paediatric diabetes: a population-based cohort study. August 2018. International Society of Exposure Sciences (ISES) and International Society for Environmental Epidemiology (ISEE) 2018 joint conference. Ottawa, Canada. [Poster](ISEE2018.pdf)

7.	Maternal and early life exposure to ambient air pollution, and the risk of pediatric inflammatory bowel disease. March 2018. University of Ottawa School of Epidemiology and Public Health Research day 2018. Ottawa Canada. [Oral](SEPH2018.pdf)

8.	Ambient Air Pollution and Childhood Inflammatory Bowel Diseases. March 2018. Health Canada, Water and Air Quality Bureau Open House. Ottawa Canada. [Oral](WAQB2018.pdf)

9. Effect of a proton pump inhibitor (PPI) deprescribing guideline on PPI drug costs in long-term care. Jan 2016. Ontario Pharmacy Research Collaboration Summit. Toronto Canada. (Poster)

10.	The effect of ginger on EGG patterns in patients with anorexia cachexia syndrome. April 2015. Biomedical Science Poster Day. University of Ottawa. Ottawa Canada. [Poster](BIM2015.pdf)
