---
title: Search trends of Covid-19
author: Michael Elten
date: '2020-03-14'
slug: search-trends-of-covid-19
categories: []
Tags:
- Data Visualization
- Ridgeplot
- GGanimate
Description: 'Looking at google search trends following the Covid-19 pandemic'

draft: true
---

This is a post in progress!

## Importing the data

For this, I will use the R package "gtrendsR" for the first time. 

```{r installation, echo=TRUE, results='hide', warning=FALSE, message=FALSE}
library("dplyr")
library("readr")
library("gtrendsR")
library("ggplot2")
library("patchwork")
```


```{r trend}
plot_trend<-function(keyword_string){
data<-gtrends(c(keyword_string), time= "2020-01-01 2020-04-03", geo = "CA")
time_trend<-data$interest_over_time %>%
  mutate(hits=ifelse(hits=="<1",0.5,hits),
         date=as.Date(date))
plot<-ggplot(data=time_trend, aes(x=date, y=as.numeric(hits), colour=keyword)) +
  geom_smooth(method="loess",span=0.4, se=FALSE) +
  theme(legend.position = "bottom")
return(plot)
}

#personal care
hair_plot<-plot_trend(keyword_string = c("how to cut hair", "barber"))
food_plot<-plot_trend(keyword_string = c("restaurant", "uber eats","food delivery"))
fitness_plot<-plot_trend(keyword_string = c("dumbells", "home gym","goodlife fitness","movati"))

#entertainment / purchasing
hoarding_plot<-plot_trend(keyword_string = "toilet paper")
videogames_plot<-plot_trend(keyword_string = "video games")
baking_plot<-plot_trend(keyword_string = c("how to bake bread","how to bake cookies","how to bake cake"))
streaming_plot<-plot_trend(keyword_string = c("disney +","netflix","hulu","prime video"))
sports_plot<-plot_trend(keyword_string = c("nba","mlb","mls","nhl"))


#parental activities
teaching_plot<-plot_trend(keyword_string = "long division")

# working from home
video_plot<-plot_trend(keyword_string = c("zoom","skype","webex"))
communication_plot<-plot_trend(keyword_string = c("slack","discord","microsoft teams"))
homeoffice_plot<-plot_trend(keyword_string = "office chair")

#Covid-19 related stuff

```


```{r}
## Combining plots: patchwork, or pubr packages...
video_plot
```

